[tools]
"npm:commitlint" = "19.8.1"
"npm:lefthook" = "1.11.14"
"npm:prettier" = "3.5.3"

# Node
# node = "22.15.1"
# pnpm = "10.12.1"
# "npm:@biomejs/biome" = "2.0.4"

# Python
# python = "3.12.11"
# uv = "0.7.13"
# ruff = "0.12.0"

[hooks]
postinstall = "lefthook install"
